import path from 'node:path';
import { sortIssues } from './scoring.js';

export function renderPrComment(result) {
  const sorted = sortIssues(result.issues);
  const blockers = sorted.filter((issue) => ['critical', 'high'].includes(issue.severity));
  const topFindings = sorted.slice(0, 10);

  const lines = [];
  lines.push('## AgentProof');
  lines.push('');
  lines.push(`**${result.scoring.verdict}** - **${result.scoring.score}/100**`);
  lines.push('');
  lines.push(decisionLine(result));
  lines.push('');
  lines.push(`Technical Gate: **${gateLine(result.technicalScoring)}**`);
  lines.push(`Design Gate: **${result.design?.enabled ? gateLine(result.design.scoring) : 'NOT RUN'}**${result.design?.enabled ? ` (${result.design.config.type}, ${result.design.mode})` : ''}`);
  if (result.designOnly) lines.push('Mode: **DesignGuard only**. Technical, docs, security, verification, and claim gates were excluded.');
  lines.push('');
  lines.push('| Signal | Value |');
  lines.push('|---|---:|');
  lines.push(`| Critical | ${result.scoring.counts.critical || 0} |`);
  lines.push(`| High | ${result.scoring.counts.high || 0} |`);
  lines.push(`| Medium | ${result.scoring.counts.medium || 0} |`);
  lines.push(`| Low | ${result.scoring.counts.low || 0} |`);
  lines.push(`| Baseline matched | ${result.baseline?.matched || 0} |`);
  lines.push(`| Suppressed | ${result.suppressedIssues?.length || 0} |`);
  lines.push('');
  lines.push(`Policy: \`${result.policy?.profileName || 'standard'}\` profile, fail-under \`${result.failUnder}\`.`);
  lines.push(`Scan: \`${result.scanMode || 'full'}\`${result.base ? ` against \`${result.base}\`` : ''}.`);
  lines.push(`Files scanned: **${result.scannedFiles}**.`);
  if (result.claim) lines.push(`Claim audited: \`${result.claim.source}\`.`);
  lines.push('');

  if (topFindings.length) {
    lines.push('### Top findings');
    lines.push('');
    for (const issue of topFindings) {
      lines.push(`- **${issue.severity.toUpperCase()}** \`${issue.id}\` - ${issue.title}${formatLocation(issue)}`);
    }
    if (sorted.length > topFindings.length) lines.push(`- ...and ${sorted.length - topFindings.length} more finding(s).`);
    lines.push('');
  } else {
    lines.push('### Findings');
    lines.push('');
    lines.push('No active findings. This does not replace human review.');
    lines.push('');
  }

  lines.push('### Verification commands');
  lines.push('');
  for (const command of result.commands.slice(0, 12)) {
    const cwd = command.cwd ? ` from \`${command.cwd}\`` : '';
    lines.push(`- \`${command.status}\` ${command.label || command.name}${cwd}: \`${command.command || ''}\``);
  }
  if (result.commands.length > 12) lines.push(`- ...and ${result.commands.length - 12} more command(s).`);
  lines.push('');

  const artifacts = artifactLines(result);
  if (artifacts.length) {
    lines.push('### Artifacts');
    lines.push('');
    for (const artifact of artifacts) lines.push(`- ${artifact}`);
    lines.push('');
  }

  if (blockers.length) {
    lines.push('### Review note');
    lines.push('');
    lines.push(`This PR has **${blockers.length} blocking finding(s)**. Fix them, rerun AgentProof, or document explicit maintainer acceptance before merge.`);
    lines.push('');
  }

  lines.push('<sub>Generated by AgentProof. Full Markdown, HTML, SARIF, receipt, and summary artifacts may be attached by CI.</sub>');
  lines.push('');

  return `${lines.join('\n')}\n`;
}

function decisionLine(result) {
  if (result.scoring.verdict === 'DESIGN REVIEW REQUIRED') return 'Decision: **design review required**. Technical proof passed, but DesignGuard found UI/product blockers.';
  if (result.scoring.verdict === 'DO NOT SHIP') return 'Decision: **block merge**. Fix critical failures first, then rerun AgentProof.';
  if (result.scoring.verdict === 'FIX BEFORE MERGE') return 'Decision: **fix before merge**. High-severity findings need owner review or remediation.';
  if (result.scoring.verdict === 'SHIP WITH CARE') return 'Decision: **review carefully**. The PR is inside the gate, but medium findings remain.';
  return 'Decision: **inside the configured gate**. Human review still applies.';
}

function artifactLines(result) {
  return [
    artifact('Markdown report', result.reportPath),
    artifact('HTML report', result.htmlPath),
    artifact('SARIF', result.sarifPath),
    artifact('PR comment', result.prCommentPath),
    artifact('Receipt', result.receiptPath),
    artifact('Summary JSON', result.summaryPath),
    artifact('History', result.history?.path)
  ].filter(Boolean);
}

function artifact(label, filePath) {
  if (!filePath) return '';
  return `${label}: \`${path.relative(process.cwd(), filePath) || filePath}\``;
}

function formatLocation(issue) {
  if (!issue.file) return '';
  return ` - \`${issue.file}${issue.line ? `:${issue.line}` : ''}\``;
}

function gateLine(scoring) {
  if (!scoring) return 'NOT RUN';
  if (scoring.score === null) return scoring.verdict || 'NOT RUN';
  return `${scoring.verdict} ${scoring.score}/100`;
}
