export function renderRecipes() {
  return [
    '# AgentProof command recipes',
    '',
    'Copy, paste, and adapt these commands depending on what you want to prove.',
    '',
    '## First local scan',
    '',
    'Start static-only when you do not want AgentProof to execute project scripts yet:',
    '',
    '```bash',
    'npx agentproof --path . --no-run-scripts',
    '```',
    '',
    'Then include detected verification scripts:',
    '',
    '```bash',
    'npx agentproof --path . --profile standard',
    '```',
    '',
    '## Strict PR gate',
    '',
    'Use this for production, client delivery, auth, billing, infrastructure, or security-sensitive work:',
    '',
    '```bash',
    'npx agentproof --path . --profile strict --fail-under 85',
    '```',
    '',
    '## Observe-only CI rollout',
    '',
    'Use this when you want reports and verdicts without blocking merges on day one:',
    '',
    '```bash',
    'npx agentproof --path . --profile strict --fail-under 85 --observe-only',
    '```',
    '',
    '## DesignFix AI rewrite',
    '',
    'Generate a reviewable rewrite for a failing landing page without touching files:',
    '',
    '```bash',
    'npx agentproof design-fix \\',
    '  --path ./landing-site \\',
    '  --design landing \\',
    '  --design-url http://localhost:3000 \\',
    '  --design-ai-provider codex-auth \\',
    '  --design-ai-model gpt-5.3-codex-spark',
    '```',
    '',
    'Apply the rewrite after review:',
    '',
    '```bash',
    'npx agentproof design-fix \\',
    '  --path ./landing-site \\',
    '  --design landing \\',
    '  --design-url http://localhost:3000 \\',
    '  --design-ai-provider codex-auth \\',
    '  --apply',
    '```',
    '',
    'Let DesignGuard create the brief, run AI, and re-score after applying:',
    '',
    '```bash',
    'npx agentproof design-improve \\',
    '  --path ./landing-site \\',
    '  --design landing \\',
    '  --design-url http://localhost:3000 \\',
    '  --design-ai-provider codex-auth \\',
    '  --target-score 90 \\',
    '  --apply',
    '```',
    '',
    'Clone and improve from a public URL when you do not have the source files:',
    '',
    '```bash',
    'npx agentproof design-fix \\',
    '  --path . \\',
    '  --from-browser \\',
    '  --design landing \\',
    '  --design-url https://example.com \\',
    '  --design-locale fr-FR \\',
    '  --clone-output ./cloned-landing \\',
    '  --design-ai-provider codex-auth \\',
    '  --apply',
    '```',
    '',
    '## Changed files only',
    '',
    'Use this in pull requests when your checkout has the base branch available:',
    '',
    '```bash',
    'npx agentproof --changed --base origin/main --profile strict',
    '```',
    '',
    '## Agent final-claim audit',
    '',
    'Ask the coding agent to write its final message to .agentproof/final-claim.md, then run:',
    '',
    '```bash',
    'npx agentproof --path . --claim .agentproof/final-claim.md',
    '```',
    '',
    'AgentProof flags claims such as "tests passed" or "production-ready" when the observed evidence does not support them.',
    '',
    '## Full review artifact bundle',
    '',
    'Use this when you want a report humans, CI, and bots can all consume:',
    '',
    '```bash',
    'npx agentproof \\',
    '  --path . \\',
    '  --profile strict \\',
    '  --fail-under 85 \\',
    '  --github-annotations \\',
    '  --sarif agentproof.sarif \\',
    '  --html agentproof-report.html \\',
    '  --pr-comment agentproof-pr-comment.md \\',
    '  --receipt agentproof-receipt.json \\',
    '  --summary agentproof-summary.json \\',
    '  --history .agentproof/history.jsonl',
    '```',
    '',
    '## Initialize a repository',
    '',
    'Create config, GitHub workflow, agent contract, and agent instruction templates:',
    '',
    '```bash',
    'npx agentproof --init --all',
    '```',
    '',
    'For stricter client delivery defaults:',
    '',
    '```bash',
    'npx agentproof --init --all --policy-pack strict-client-delivery',
    '```',
    '',
    '## Demo this repository',
    '',
    'When running from the AgentProof source checkout:',
    '',
    '```bash',
    'npm run demo:claim',
    'npm run demo:good',
    'npm run demo:monorepo',
    '```',
    '',
    'Before package publication, replace npx agentproof with:',
    '',
    '```bash',
    'node ./bin/agentproof.mjs',
    '```'
  ].join('\n');
}
