export function renderTroubleshooting() {
  return [
    '# AgentProof troubleshooting',
    '',
    'AgentProof is designed to fail loudly when evidence is missing, risky, or below your policy threshold. A failure is a review signal, not a dead end.',
    '',
    '## Start here',
    '',
    '1. Read the top findings in `AGENT_PROOF_REPORT.md`.',
    '2. Check whether scripts were allowed to run.',
    '3. Decide whether the finding is real risk, known debt, or a false positive.',
    '4. Fix real risk, baseline known debt, and suppress false positives with an expiry date.',
    '',
    '## Common failures',
    '',
    '### The score is too low',
    '',
    'Run a static-only scan first to separate code smells from command failures:',
    '',
    '```bash',
    'npx agentproof --path . --no-run-scripts',
    '```',
    '',
    'Then run with the profile you actually want to enforce:',
    '',
    '```bash',
    'npx agentproof --path . --profile standard --fail-under 80',
    '```',
    '',
    'If this is a legacy repo, create a baseline instead of lowering standards forever:',
    '',
    '```bash',
    'npx agentproof --path . --update-baseline .agentproof/baseline.json',
    'npx agentproof --path . --baseline .agentproof/baseline.json --profile standard',
    '```',
    '',
    'For a non-blocking rollout, keep the verdict but force exit code 0:',
    '',
    '```bash',
    'npx agentproof --path . --profile strict --fail-under 85 --observe-only',
    '```',
    '',
    '### The agent claim failed',
    '',
    'AgentProof flags unsupported final claims. If the agent says "tests passed", a passing test command needs to be observed in the run.',
    '',
    'Safer final claim:',
    '',
    '```text',
    'Implemented the requested change. Build and lint passed. I did not run the full test suite.',
    '```',
    '',
    'Risky final claim:',
    '',
    '```text',
    'Done. Everything is tested and production-ready.',
    '```',
    '',
    '### Project scripts should not run',
    '',
    'Use:',
    '',
    '```bash',
    'npx agentproof --path . --no-run-scripts',
    '```',
    '',
    'This keeps the scan static and avoids executing package scripts in untrusted repositories.',
    '',
    '### Changed-file mode found no files or failed',
    '',
    'Make sure the base ref exists locally:',
    '',
    '```bash',
    'git fetch origin main',
    'npx agentproof --changed --base origin/main',
    '```',
    '',
    'In GitHub Actions, use `fetch-depth: 0` on `actions/checkout` so the base ref is available.',
    '',
    '### A secret finding looks like a false positive',
    '',
    'Do not paste real secrets into issues. Redact values before sharing examples.',
    '',
    'Options:',
    '',
    '- rename fake values so they no longer look like credentials;',
    '- move real secrets to environment variables or secret stores;',
    '- suppress a confirmed false positive with owner, reason, and expiry in `agentproof.config.json`.',
    '',
    '### CI cannot post a PR comment',
    '',
    'Keep generating `agentproof-pr-comment.md` as an artifact, or add `pull-requests: write` only when your repository policy allows it.',
    '',
    'If you still want inline signal without PR comment permissions, enable GitHub annotations:',
    '',
    '```bash',
    'npx agentproof --path . --github-annotations',
    '```',
    '',
    '### The report is noisy on first adoption',
    '',
    'Use a rollout path:',
    '',
    '```bash',
    'npx agentproof --path . --no-run-scripts',
    'npx agentproof --path . --profile relaxed --fail-under 70',
    'npx agentproof --path . --profile standard --fail-under 80',
    '```',
    '',
    'Then move high-risk repos to strict mode:',
    '',
    '```bash',
    'npx agentproof --path . --profile strict --fail-under 85',
    '```',
    '',
    '## What to include in bug reports',
    '',
    'Include:',
    '',
    '- AgentProof version;',
    '- command used;',
    '- sanitized top findings;',
    '- whether `--no-run-scripts` was used;',
    '- relevant config without secrets;',
    '- minimal reproduction when possible.',
    '',
    'Never include real tokens, private customer code, production logs, or unredacted `.env` files.'
  ].join('\n');
}
